name: Docker image Builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file resume/Dockerfile --tag latexresume
    - name: export environment variable
      run: export CR_PAT=${{ secrets.BUILD_GITHUB_TOKEN }}
    - name: pass github token into github registry
      run: echo $CR_PAT | docker login ghcr.io -u jaredstemper --password-stdin
    - name: push new image into github registry 
      run: docker push ghcr.io/jarestemperwebsite/latexresume:latest
