name: Build Current Resume

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: pass github token into github registry
      run: echo ${{ secrets.BUILD_GITHUB_TOKEN }} | docker login ghcr.io -u JaredStemper --password-stdin
    - name: Build the Docker image
      run: docker pull ghcr.io/jaredstemper/latexresume:latest
    - name: run docker image
      run: docker run --rm -v $(pwd)/resume:/input -v $(pwd)/resume/build:/output ghcr.io/jaredstemper/latexresume:latest