name: Build Current Resume 

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/docker-latexBuild.yml'
      - 'resume/JaredStemper_Resume.tex'
      - 'resume/resume.cls'
      - 'assets/resume'

jobs:
  permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: pass github token into github registry
      run: echo ${{ secrets.BUILD_GITHUB_TOKEN }} | docker login ghcr.io -u JaredStemper --password-stdin
    - name: Build the Docker image
      run: docker pull ghcr.io/jaredstemper/latexresume:latest
    - name: run docker image
      run: docker run --rm -v $(pwd)/resume:/input -v $(pwd)/resume/:/output -v $(pwd)/assets/resume:/assets ghcr.io/jaredstemper/latexresume:latest
    - name: copy current pdf out of build folder
      run: cp $(pwd)/resume/build/JaredStemper_Resume.pdf $(pwd)/resume/JaredStemper_Resume.pdf
    - name: check git status
      run: git status
    - name: add staged
      run: git add -A
    - name: commit with current date
      run: git commit -c "Build Resume Workflow: updated resume based on changes as of $(date +%c --utc)"
    - name: push changes
      run: git push
