name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file resume/Dockerfile --tag latexresume
    - name: run docker image
      run: docker run --rm -v $(pwd)/resume:/input -v $(pwd)/resume/build:/output latexresume
